### ISSUE TITLE
Perform factor return calculations with polars-ols?

### ISSUE THREAD

**Issue by oleicht** [0xfdf/toraniko#4]
Hello,

[The factor return calculations](https://github.com/0xfdf/toraniko/blob/253ce7044ef33eb718e671e9f918a88ba5fa3350/toraniko/model.py#L69) are currently performed in numpy. This causes some copying of data. If you're OK with a dependence on [polars-ols](https://github.com/azmyrajab/polars_ols/), it would be straightforward to get rid of numpy and by extension the copying. This should give some nice speed-ups.

Let me know if you're interested, happy to make a PR.

**Comment by 0xfdf** [comment]
I appreciate the issue, thanks for taking the time. 

I can see your point, but I have a very high bar for introducing further dependencies. I would rather try to find a way to reduce the data copying/memory footprint while staying with numpy, if possible.
