### ISSUE TITLE
Custom Factor Creation

### ISSUE THREAD

**Issue by vantubbe** [0xfdf/toraniko#7]
Apologies as this is not an issue. Any chance of expanding the readme to include example(s) of adding a custom factor? Really appreciate your contribution!

**Comment by 0xfdf** [comment]
Certainly. I will add documentation improvements in the open PR for the upcoming version. A few workflow examples are on my list.

Thanks for the feedback.

**Comment by vantubbe** [comment]
That's great! Thank you again, big fan of your twitter feed too.
